# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  # Init
  initialize:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  
  # Eslint run
  code_linting:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0
    steps:
      - run:
          - name: Code Syntax check
          - command: eslint . --fix


# Pipeline
workflows:
  version: 2
  pipeline:
    jobs:
      - initialize
      - code_linting:
        requires:
          - initialize
      - store_test_results:
          path: test-results.xml
          requires:
            - initialize
            - code_linting